### ISSUE TITLE
Client ID / Secret?

### ISSUE THREAD

**Issue by ghost** [larabros/oauth2-psn#3]
Hi,

thanks for your work, but would you mind explaining, how to use it? I mean... I havent found any instructions how nor where to register an app at PSN to obtain the client id / client secret that is required to use your script.

Any help is appreciated.

**Comment by hassankhan** [comment]
Hi, I cannot provide those details since they are property of Sony Computer Entertainment. If you have a PSN dev account, you can create an OAuth application yourself.

There is some documentation available in [DOCS.md](../DOCS.md), hope that helps.

**Comment by ghost** [comment]
You got me wrong, i guess.

> If you have a PSN dev account, you can create an OAuth application yourself.

That was the question. Where can we create it? The only thing i can find on their website is for Lifelog ([Authentication](https://developer.sony.com/develop/services/lifelog-api/authentication/)) but not for PSN itself.

Or do we have to register via [SCE DevNet](https://www.companyregistration.playstation.com/SCEInternetApplications/AreaNewLicensee/MainSystem/CFModules/NewLicensee/snl_master_template.cfm)?

**Comment by hassankhan** [comment]
Indeed, you would have to be a registered SCE DevNet user (and if memory serves correctly, make a request to create a new OAuth2 application).
